version: '3.7'

services:
  jaeger-collector:
    container_name: jaeger-collector
    image: jaegertracing/jaeger-collector:1.39.0
    environment:
      - SAMPLER_TYPE=probabilistic
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=root
      - ES_PASSWORD=root
      - SAMPLING_INITIAL_SAMPLING_PROBABILITY=0.5
      - ES_USE_ALIASES=true
    ports:
      - "14250:14250"
      - "14269:14269" # health check
    restart: on-failure

  jaeger-query:
    container_name: jaeger-query
    image: jaegertracing/jaeger-query:1.39.0
    volumes:
      - "./jaeger/jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=root
      - ES_PASSWORD=root
      - ES_USE_ALIASES=true
    ports:
      - "16686:16686"
      - "16687:16687" #healthy port
    restart: on-failure

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.66.0
    volumes:
      - "./otel-collector/otel-jaeger-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "13133:13133"
      - "8888:8888"
    depends_on:
      - jaeger-collector
